// src/components/VideoUploadProcessing.svelte
<script lang="ts">
  import { drawLandmarks } from "@mediapipe/drawing_utils";
  import { FaceMesh, type Results } from "@mediapipe/face_mesh";
  import { onDestroy, onMount } from "svelte";
  import { writable } from "svelte/store";
  import { createSession } from "../scripts/session";
  import { userSettings } from '../scripts/settings';

  import {
      applyAffineTransformation,
      calculateAffineTransformation,
  } from "../scripts/affineTransformation";
  import {
      LEFT_EYE_CORNER,
      LEFT_IRIS_CENTER,
      NOSE_TIP,
      RIGHT_EYE_CORNER,
      RIGHT_IRIS_CENTER,
      getLandmarks,
      getNormalizedIrisPosition,
  } from "../scripts/utils";

  import type { Coordinates } from "../scripts/affineTransformation";
  import { applySmoothing } from "../scripts/smoothing";
  import { WebSocketConnection } from "../scripts/websocket";
  // import { number } from "astro:schema";
  // import { ProbabilityGraph } from "../scripts/graph";  // Import the ProbabilityGraph class

  // UI state variables
  let isPlaying = false;
  let videoLoaded = false;
  let isProcessing = false;
  let isLoadingFile = false;

  // Offscreen processing variables
  let videoElement: HTMLVideoElement;
  let processingCanvas: HTMLCanvasElement;
  let offscreenCtx: CanvasRenderingContext2D | null;
  let faceMesh: FaceMesh;
  let animationFrameId: number;

  const canvasWidth = 640;
  const canvasHeight = 480;

  const WEBSOCKET_URL = import.meta.env.PUBLIC_WS_PORT;

  let variance: number | null = null;
  let acceleration: number | null = null;
  let probability: number | null = null;

  let ws: WebSocketConnection | null = null;
  // let probabilityGraph: ProbabilityGraph;  // Declare a ProbabilityGraph instance

  let isModalVisible = writable(false);
  let sessionName = "";
  let sessionCreated = false;
  let startTime = new Date().toISOString();
  let initialNoseTip: Coordinates | null = null; // Track the initial nose tip position

  let previousXValues: number[] = [];
  let previousYValues: number[] = [];

  let remainingTime = 0;
  let countdownTimer: number;

  let sensitivity: number | null = null;

   export const shouldShowGraph = writable(false);

   let affineTransformEnabled = writable(false);

   // Log the settings whenever they change
   userSettings.subscribe((settings: any) => {
       console.log("User settings:", settings);
       sensitivity = settings.sensitivity;
       affineTransformEnabled.set(settings.affine ?? false);
     });

  function handleWebSocketMessage(data: any) {
    if (
      data.variance !== undefined &&
      data.acceleration !== undefined &&
      data.probability !== undefined
    ) {
      probability = data.probability;
      console.log("Probability:", probability);

      // Update the probability graph with the new probability value
      // if (probability !== null) {
      //   probabilityGraph.updateProbability(probability);
      // }
    }
  }

  function startWebSocket() {
    if (ws) ws.close(); // Ensure no duplicate connections

    ws = new WebSocketConnection(WEBSOCKET_URL, handleWebSocketMessage);
    ws.start();
  }

  function processFrame() {
    if (faceMesh && videoElement) {
      faceMesh.send({ image: videoElement });
    }
  }

  // Start the countdown when video metadata is available
  function startCountdown() {
    clearInterval(countdownTimer);
    remainingTime = videoElement.duration;
    countdownTimer = setInterval(() => {
      remainingTime = Math.max(remainingTime - 1, 0);
      if (remainingTime === 0) {
        clearInterval(countdownTimer);
      }
    }, 1000);
  }

  function stopCountdown() {
    clearInterval(countdownTimer);
  }

  onMount(() => {
    // Initialize the probability graph
    // const graphCanvas = document.createElement("canvas");
    // graphCanvas.width = canvasWidth;
    // graphCanvas.height = 200; // Set a fixed height for the graph
    // document.body.appendChild(graphCanvas);
    // probabilityGraph = new ProbabilityGraph(graphCanvas);

    // Create a hidden video element for loading and playback
    videoElement = document.createElement("video");
    videoElement.style.display = "none";
    // Ensure inline playback (especially for mobile)
    videoElement.setAttribute("playsinline", "true");
    document.body.appendChild(videoElement);

    // === IMPORTANT ===
    // This "ended" event closes the modal automatically when the video finishes playing.
    // Instead of automatically ending the session when the video ends,
    // show the modal so the user can input the session name.
    videoElement.onended = () => {
      isModalVisible.set(true);
    };

    // Create a hidden canvas element for processing
    processingCanvas = document.createElement("canvas");
    processingCanvas.width = canvasWidth;
    processingCanvas.height = canvasHeight;
    processingCanvas.style.display = "none";
    document.body.appendChild(processingCanvas);
    offscreenCtx = processingCanvas.getContext("2d");

    // Initialize MediaPipe FaceMesh
    faceMesh = new FaceMesh({
      locateFile: (file) =>
        `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`,
    });
    faceMesh.setOptions({
      maxNumFaces: 1,
      refineLandmarks: true,
      minDetectionConfidence: 0.43,
      minTrackingConfidence: 0.5,
    });

    if (!offscreenCtx) return;

    // Process results – drawing to the offscreen canvas (not displayed)
    // Inside the onResults function, after drawing landmarks:
    faceMesh.onResults((results: Results) => {
      if (offscreenCtx) {
        offscreenCtx.save();
        offscreenCtx.clearRect(
          0,
          0,
          processingCanvas.width,
          processingCanvas.height,
        );
        offscreenCtx.drawImage(
          results.image,
          0,
          0,
          processingCanvas.width,
          processingCanvas.height,
        );
      }

      if (results.multiFaceLandmarks) {
        for (const landmarks of results.multiFaceLandmarks) {
          const irisCenters = getLandmarks(landmarks, [
            LEFT_IRIS_CENTER,
            RIGHT_IRIS_CENTER,
          ]);
          if (offscreenCtx) {
            drawLandmarks(offscreenCtx, irisCenters, {
              color: "#FF0000",
              lineWidth: 2,
            });

            const eyeCorners = getLandmarks(landmarks, [
              LEFT_EYE_CORNER,
              RIGHT_EYE_CORNER,
            ]);
            drawLandmarks(offscreenCtx, eyeCorners, {
              color: "#FF0000",
              lineWidth: 1,
            });

            const noseTip = getLandmarks(landmarks, [NOSE_TIP]);
            drawLandmarks(offscreenCtx, noseTip, {
              color: "#FF0000",
              lineWidth: 1,
            });
          }

          // Smoothing iris positions
          const { normX, normY, timestamp } = getNormalizedIrisPosition(
            landmarks,
            processingCanvas.width,
            processingCanvas.height,
          );

          // Apply smoothing to the iris position
          const smoothedNormX = applySmoothing(normX, previousXValues);
          const smoothedNormY = applySmoothing(normY, previousYValues);

          // Track the current nose tip for affine transformation
          const currentNoseTip: Coordinates = getLandmarks(landmarks, [
            NOSE_TIP,
          ])[0];

          if (initialNoseTip && affineTransformEnabled) {
            // Calculate the affine transformation matrix based on initial and current nose tip positions
            const transformationMatrix = calculateAffineTransformation(
              initialNoseTip,
              currentNoseTip,
            );

            // Apply the transformation to all landmarks (using smoothed iris position)
            const transformedLandmarks = landmarks.map((landmark) =>
              applyAffineTransformation(landmark, transformationMatrix),
            );

            // Draw the transformed landmarks on the canvas
            if (offscreenCtx) {
              drawLandmarks(offscreenCtx, transformedLandmarks, {
                color: "#0000FF",
                lineWidth: 2,
              });
            }
          }

          const timestampInSeconds = timestamp / 1000; // Convert timestamp to seconds

          const metrics = {
            x: smoothedNormX,
            y: smoothedNormY,
            time: timestampInSeconds,
            sensitivity: sensitivity ?? 1.0
          };

          if (ws) {
            ws.sendMessage(metrics);
            console.log("WebSocket Sent:", metrics);
          }
        }
      }
      if (offscreenCtx) {
        offscreenCtx.restore();
      }
    });

    // === Pre-warm mediapipe: perform a dummy send on a blank frame ===
    if (offscreenCtx) {
      // Draw a blank frame (or any minimal dummy content)
      offscreenCtx.fillStyle = "#000";
      offscreenCtx.fillRect(0, 0, canvasWidth, canvasHeight);
      // Send the blank frame. This call will download and compile WASM, create a WebGL context, etc.
      faceMesh
        .send({ image: processingCanvas })
        .catch((error) => console.error("Error during warm-up:", error));
    }

    // Start WebSocket connection
    startWebSocket();
  });

  onDestroy(() => {
    if (videoElement) {
      videoElement.pause();
      videoElement.src = "";
      videoElement.remove();
    }
    if (animationFrameId) {
      cancelAnimationFrame(animationFrameId);
    }
    if (ws) {
      ws.close();
    }
  });

  // Process the video frame by frame:
  async function processVideoFrame() {
    // Check immediately: if paused or ended, stop processing.
    if (videoElement.paused || videoElement.ended) {
      isProcessing = false;
      return;
    }
    if (offscreenCtx) {
      offscreenCtx.drawImage(videoElement, 0, 0, canvasWidth, canvasHeight);
    }
    // Check again before processing the frame.
    if (videoElement.paused || videoElement.ended) {
      isProcessing = false;
      return;
    }
    try {
      await faceMesh.send({ image: processingCanvas });
    } catch (error) {
      console.error("Error processing frame:", error);
    }
    // If video got paused while processing, stop here.
    if (videoElement.paused || videoElement.ended) {
      isProcessing = false;
      return;
    }
    animationFrameId = requestAnimationFrame(processVideoFrame);
  }

  // Triggered when a file is selected.
  function handleVideoUpload(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files ? input.files[0] : null;
    if (file) {
      const url = URL.createObjectURL(file);
      videoElement.src = url;
      // Start countdown once metadata is available (duration etc.)
      videoElement.onloadedmetadata = () => {
        startCountdown();
      };
      videoElement.onloadeddata = () => {
        // Close the modal automatically when the video is done uploading
        isModalVisible.set(false);
        videoLoaded = true;
        isPlaying = true;
        isProcessing = true;
        videoElement.play();
        processVideoFrame();
      };
    }
  }

  // Control handlers
  function handlePlay() {
    if (videoLoaded && videoElement.paused) {
      isPlaying = true;
      isProcessing = true;
      videoElement.play();
      processVideoFrame();
    }
  }

  function handlePause() {
    if (videoLoaded && !videoElement.paused) {
      isPlaying = false;
      // Immediately stop processing and cancel the next frame.
      isProcessing = false;
      videoElement.pause();
      cancelAnimationFrame(animationFrameId);
    }
  }

  function handleStop() {
    if (!sessionCreated) {
      isModalVisible.set(true);
    } else {
      endSession();
    }
  }

  function endSession() {
    if (!sessionCreated) {
      const sessionData = {
        name: sessionName || "Session", // Default name if none provided
        start_time: startTime,
        end_time: new Date().toISOString(),
        var_min: variance ?? 0,
        var_max: variance ?? 0,
        acc_min: acceleration ?? 0,
        acc_max: acceleration ?? 0,
      };

      createSession(sessionData);
      sessionCreated = false;
      isModalVisible.set(false);
    }
    if (videoLoaded) {
      isPlaying = false;
      videoLoaded = false;
      videoElement.pause();
      videoElement.currentTime = 0;
      if (offscreenCtx) {
        offscreenCtx.clearRect(0, 0, canvasWidth, canvasHeight);
      }
    }
    // window.location.href = "/dashboard";
  }
</script>

<!--
  1) Loading Spinner for when the file is being selected and loaded
     If you want it in a different place, move this {#if isLoadingFile} block
-->
{#if isLoadingFile}
  <div class="spinner mt-4 flex justify-center">
    <div class="loader"></div>
  </div>
{/if}

{#if videoLoaded && isPlaying}
  <div class="mt-2 text-center">
    Estimated Time Remaining: {Math.floor(remainingTime)} sec
  </div>
{/if}

<div
  class="flex flex-col items-center justify-center rounded-lg border-4 border-primary opacity-90 shadow-glow bg-base-200 m-4 p-4"
>
  <!-- Processing indicator: Spinner while processing, Pause symbol when paused -->
  {#if isProcessing}
    <div class="spinner mt-4 flex justify-center">
      <div class="loader"></div>
    </div>
  {:else if videoLoaded && !isPlaying}
    <div class="pause-icon mt-4 flex justify-center">
      <div class="pause-symbol">&#10074;&#10074;</div>
    </div>
  {/if}

  <!-- Visible file input with original styling -->
  <input
    type="file"
    accept="video/*"
    on:change={handleVideoUpload}
    id="fileInput"
    class="flex p-2 bg-secondary hover:text-secondary-content rounded-md w-fit my-2 shadow-glow hover:scale-105 transition-transform"
    disabled={isLoadingFile}
  />

  {#if videoLoaded}
    <div class="flex w-full font-semibold">
      <!-- Example: your Play, Pause, Stop buttons -->
      <!--
      <button on:click={handlePlay}>Play</button>
      <button on:click={handlePause}>Pause</button>
      <button on:click={handleStop}>Stop</button>
      -->
    </div>
  {/if}

  <!-- Session Name Modal -->
  <!-- Session Name Modal -->
  {#if $isModalVisible}
  <div
    class="fixed inset-0 flex justify-center items-center z-50"
    style="background-color: black !important;"
  >
    <div
      class="p-6 rounded-lg border-4 border-secondary shadow-glow w-96"
      style="background-color: #000000;"
    >
      <h2
        class="font-mono font-semibold text-center text-2xl text-primary mb-4"
      >
        Enter Session Name
      </h2>
      <p class="text-center text-base-content mb-4">
        Please name your session to save the results.
      </p>
      <input
        type="text"
        bind:value={sessionName}
        class="border border-accent p-2 rounded-md w-full mb-4
               bg-base-200 text-base-content focus:border-info focus:bg-neutral focus:outline-none ease-in-out duration-150"
        placeholder="Session Name"
      />
      <div class="flex justify-between">
        <button
          on:click={() => isModalVisible.set(false)}
          class="bg-neutral border border-warning hover:border-error hover:bg-error p-2 rounded-lg transition-colors duration-150 hover:text-error-content"
        >
          Cancel
        </button>
        <button
          on:click={endSession}
          class="bg-neutral border border-info hover:border-success hover:bg-success p-2 rounded-lg transition-colors duration-150 hover:text-success-content"
        >
          Submit
        </button>
      </div>
    </div>
  </div>
{/if}

</div>

<style>
  /* Basic spinner styling */
  .spinner {
    margin: 1rem auto;
  }
  .loader {
    border: 8px solid rgba(0, 0, 0, 0.1);
    border-top: 8px solid #3498db; /* or your color choice */
    border-radius: 50%;
    width: 48px;
    height: 48px;
    animation: spin 1s linear infinite;
  }
  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
  /* Optional pause symbol styling */
  .pause-symbol {
    font-size: 2rem;
    color: #fff;
  }
</style>

// src/components/VideoUploadProcessing.tsx
import React, { useRef, useEffect, useState } from "react";
import { FaceMesh, type Results } from "@mediapipe/face_mesh";
import { drawLandmarks } from "@mediapipe/drawing_utils";
import {
  LEFT_IRIS_CENTER,
  RIGHT_IRIS_CENTER,
  LEFT_EYE_CORNER,
  RIGHT_EYE_CORNER,
  NOSE_TIP,
  getNormalizedIrisPosition,
  getLandmarks,
} from "../scripts/utils";
import { transform, translate, scale, applyToPoint } from "transformation-matrix";

const VideoUploadProcessing: React.FC = () => {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const faceMeshRef = useRef<FaceMesh | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [videoLoaded, setVideoLoaded] = useState(false);
  const [key, setKey] = useState(0);

  const alignFace = (landmarks: any[], canvasWidth: number, canvasHeight: number) => {
    const leftIris = getLandmarks(landmarks, [LEFT_IRIS_CENTER]);
    const rightIris = getLandmarks(landmarks, [RIGHT_IRIS_CENTER]);
    const noseTip = getLandmarks(landmarks, [NOSE_TIP]);

    if (!leftIris || !rightIris || !noseTip) {
      console.error("One or more landmarks are undefined.");
      return null;
    }

    const leftEyeCenter = { x: leftIris.x * canvasWidth, y: leftIris.y * canvasHeight };
    const rightEyeCenter = { x: rightIris.x * canvasWidth, y: rightIris.y * canvasHeight };

    const deltaX = rightEyeCenter.x - leftEyeCenter.x;
    const deltaY = rightEyeCenter.y - leftEyeCenter.y;
    const angle = Math.atan2(deltaY, deltaX) * (180 / Math.PI);

    const desiredDist = 100; // Desired distance between eyes in pixels
    const currentDist = Math.sqrt(deltaX ** 2 + deltaY ** 2) || 1e-6;
    const scaleFactor = desiredDist / currentDist;

    const eyesCenter = {
      x: (leftEyeCenter.x + rightEyeCenter.x) / 2,
      y: (leftEyeCenter.y + rightEyeCenter.y) / 2,
    };

    const scaleMatrix = scale(scaleFactor, scaleFactor);
    const translationMatrix = translate(
      canvasWidth / 2 - eyesCenter.x,
      canvasHeight / 2 - eyesCenter.y
    );

    const combinedMatrix = transform(scaleMatrix, translationMatrix);

    const transformedLandmarks = landmarks.map((lm: any) => {
      const transformedPoint = applyToPoint(combinedMatrix, {
        x: lm.x * canvasWidth,
        y: lm.y * canvasHeight,
      });

      return {
        x: transformedPoint.x / canvasWidth,
        y: transformedPoint.y / canvasHeight,
      };
    });

    return transformedLandmarks;
  };

  useEffect(() => {
    const canvasElement = canvasRef.current;
    const canvasCtx = canvasElement?.getContext("2d") ?? null;

    if (canvasElement && canvasCtx) {
      faceMeshRef.current = new FaceMesh({
        locateFile: (file) =>
          `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`,
      });

      faceMeshRef.current.setOptions({
        maxNumFaces: 1,
        refineLandmarks: true,
        minDetectionConfidence: 0.43,
        minTrackingConfidence: 0.5,
      });

      faceMeshRef.current.onResults((results: Results) => {
        if (!canvasCtx) return;
        canvasCtx.save();
        canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
        canvasCtx.drawImage(
          results.image,
          0,
          0,
          canvasElement.width,
          canvasElement.height
        );
        if (results.multiFaceLandmarks) {
          for (const landmarks of results.multiFaceLandmarks) {
            // const irisCenterLandmarks = getLandmarks(landmarks, [
            //   LEFT_IRIS_CENTER,
            //   RIGHT_IRIS_CENTER,
            // ]);
            // drawLandmarks(canvasCtx, irisCenterLandmarks, {
            //   color: "#FF0000",
            //   lineWidth: 1,
            // });
            // const eyeCornerLandmarks = getLandmarks(landmarks, [
            //   LEFT_EYE_CORNER,
            //   RIGHT_EYE_CORNER,
            // ]);
            // drawLandmarks(canvasCtx, eyeCornerLandmarks, {
            //   color: "#FF0000",
            //   lineWidth: 1,
            // });
            // const noseLandmarks = getLandmarks(landmarks, [NOSE_TIP]);
            // drawLandmarks(canvasCtx, noseLandmarks, {
            //   color: "#FF0000",
            //   lineWidth: 1,
            // });
            
            console.log("Original Landmarks:", landmarks);
            const transformedLandmarks = alignFace(
              landmarks,
              canvasElement.width,
              canvasElement.height
            );
            if (!transformedLandmarks) {
              console.error("Failed to transform landmarks.");
              continue;
            }
            
            // Extract only the specific five landmarks
            const specificLandmarks = [
              transformedLandmarks[LEFT_EYE_CORNER],
              transformedLandmarks[RIGHT_EYE_CORNER],
              transformedLandmarks[LEFT_IRIS_CENTER],
              transformedLandmarks[RIGHT_IRIS_CENTER],
              transformedLandmarks[NOSE_TIP],
            ];
            console.log("Transformed Specific Landmarks:", specificLandmarks);
            // Draw transformed landmarks
            specificLandmarks.forEach((point) => {
              drawLandmarks(canvasCtx, [point], {
                color: "#FF0000",
                lineWidth: 1,
              });
            });           

            // Log normalized coordinates for debugging
            const { normX, normY, timestamp } = getNormalizedIrisPosition(
              transformedLandmarks,
              canvasElement.width,
              canvasElement.height
            );
            console.log(
              `Normalized Iris Position: X: ${normX}, Y: ${normY}, Timestamp: ${timestamp}`
            );
          }
        }
        canvasCtx.restore();
      });
    }
  }, [key]);

  const handleVideoUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file && videoRef.current) {
      const videoElement = videoRef.current;
      videoElement.src = URL.createObjectURL(file);
      videoElement.onloadeddata = () => {
        setVideoLoaded(true);
        setIsPlaying(true);
        videoElement.play();
        processVideo();
      };
    }
  };

  const processVideo = () => {
    const videoElement = videoRef.current;
    const canvasElement = canvasRef.current;
    if (videoElement && canvasElement && faceMeshRef.current) {
      const onVideoFrame = async () => {
        if (!videoElement.paused && !videoElement.ended) {
          await faceMeshRef.current!.send({ image: videoElement });
          requestAnimationFrame(onVideoFrame);
        }
      };
      requestAnimationFrame(onVideoFrame);
    }
  };

  const handlePlay = () => {
    if (videoRef.current) {
      setIsPlaying(true);
      videoRef.current.play();
      processVideo();
    }
  };

  const handlePause = () => {
    if (videoRef.current) {
      setIsPlaying(false);
      videoRef.current.pause();
    }
  };

  const handleStop = () => {
    setIsPlaying(false);
    setVideoLoaded(false);
    setKey((prevKey) => prevKey + 1);
    const canvasElement = canvasRef.current;
    const canvasCtx = canvasElement?.getContext("2d") ?? null;
    if (canvasCtx) {
      canvasCtx.clearRect(0, 0, canvasElement!.width, canvasElement!.height);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center border-accent-magenta rounded-lg border-2 opacity-90 shadow-glow bg-base-light dark:bg-base">
      <input
        type="file"
        accept="video/*"
        onChange={handleVideoUpload}
        className="flex text-white dark:text-gray-300 p-2 bg-gradient-to-b from-accent-magenta to-accent-green rounded-md w-fit my-2 shadow-glow hover:scale-105 transition-transform"
      />
      <div className="border-b-2 border-accent-magenta">
        <video
          key={key}
          ref={videoRef}
          width="640"
          height="480"
          style={{ display: "none" }}
        ></video>
        <canvas
          ref={canvasRef}
          width="640"
          height="480"
          className="m-2 rounded bg-gradient-to-r from-accent-cyan via-accent-magenta to-accent-green shadow-glow"
        ></canvas>
      </div>
      {videoLoaded && (
        <div className="flex w-full font-semibold text-lg text-white dark:text-gray-300">
          <button
            onClick={handlePlay}
            disabled={isPlaying}
            className={`bg-accent-cyan m-2 ml-3 my-2 py-4 rounded-md w-full h-full text-black dark:text-white 
                    hover:bg-accent-green hover:scale-105 hover:shadow-glow transition-transform ${
                      isPlaying ? "opacity-50 cursor-not-allowed" : ""
                    }`}
          >
            Play
          </button>
          <button
            onClick={handlePause}
            disabled={!isPlaying}
            className={`bg-accent-yellow m-2 py-4 rounded-md w-full h-full text-black dark:text-white 
                    hover:bg-accent-orange hover:scale-105 hover:shadow-glow transition-transform ${
                      !isPlaying ? "opacity-50 cursor-not-allowed" : ""
                    }`}
          >
            Pause
          </button>
          <button
            onClick={handleStop}
            disabled={isPlaying}
            className={`bg-accent-magenta m-2 mr-3 py-4 rounded-md w-full h-full text-black dark:text-white 
                    hover:bg-accent-red hover:scale-105 hover:shadow-glow-magenta transition-transform ${
                      isPlaying ? "opacity-50 cursor-not-allowed" : ""
                    }`}
          >
            Stop
          </button>
        </div>
      )}
    </div>
  );
};

export default VideoUploadProcessing;
